src/items/urls.py
from __future__ import absolute_import

from django.conf.urls import url
from .views import ShopView as Shop

urlpatterns = [
    url(r"^shoppe/$", Shop.as_view(), name="items-shop"),
]

src/spirithunter/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles import views

from rest_framework import routers

from items.views import (
    ItemViewSet,
    InventoryViewSet,
    RecipeViewSet,
    IngredientViewSet
)
from spirits.views import SpiritViewSet, SpiritFinderViewSet
from users.views import UserViewSet

from .views import IndexView as Index
from .views import JavascriptVariablesView as JavascriptVariables
from .views import HumansView as Humans
from .views import RobotsView as Robots
from .views import AboutView as About
from .views import DefaultView as Default

admin.autodiscover()

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"explore", SpiritFinderViewSet)
router.register(r"spirits", SpiritViewSet)
router.register(r"items", ItemViewSet)
router.register(r"inventory", InventoryViewSet)
router.register(r"recipes", RecipeViewSet)
router.register(r"ingredients", IngredientViewSet)

urlpatterns = [

    url(r'^api/', include(router.urls, namespace="drf")),

    url(r'^variables.js', JavascriptVariables.as_view(), name="javascript"),

    url(r'^$', Index.as_view(), name="index"),
    url(r"^about/$", About.as_view(), name="about"),
    url(r"^default/$", Default.as_view(), name="default"),

    url(r"^users/", include("users.urls")),
    url(r"^spirits/", include("spirits.urls")),
    url(r"^items/", include("items.urls")),

    url(r'^humans.txt$', Humans.as_view(), name="humanstxt"),
    url(r'^robots.txt$', Robots.as_view(), name="robotstxt"),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),

]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve, {"show_indexes": True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ]

src/users/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, get_user_model
from django.core.mail import send_mail
from django.core.urlresolvers import reverse


class LoginForm(AuthenticationForm):

    next = forms.CharField(
        max_length=1024,
        widget=forms.widgets.HiddenInput,
        required=False
    )

    def __init__(self, request, *a, **kwa):

        AuthenticationForm.__init__(self, request, *a, **kwa)

        self.fields["next"].initial = request.GET.get("next", "")

        self.request = request
        self.redirect = None

    def clean_next(self):
        self.redirect = self.cleaned_data.get("next")
        return self.redirect

    def login(self):
        login(self.request, self.user_cache)


class RegistrationForm(forms.ModelForm):

    password_confirm = forms.CharField(widget=forms.widgets.PasswordInput)

    class Meta:
        model = get_user_model()
        exclude = [
            "is_referrer", "last_login", "is_superuser", "groups",
            "user_permissions", "is_staff", "is_active", "tz"
        ]

    def __init__(self, request, *a, **kwa):

        self.request = request

        forms.ModelForm.__init__(self, *a, **kwa)

        self.fields["password"].widget = forms.widgets.PasswordInput()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError(
                'That email is already registered.  If you\'ve forgotten your '
                'password, you can use the "Forgot Password?" link under the '
                'login form.'
            )
        return email

    def clean(self):

        cleaned_data = self.cleaned_data

        self.instance.is_active = False

        return cleaned_data

    def save(self, *a, **kwa):

        self.instance.set_password(self.cleaned_data["password"])

        send_mail(
            "Confirm your email address on RxLenses.ca",
            "Thank you for registering with RxLenses.ca!  As we use email to "
            "send confirmations of orders, we need to confirm that the"
            "address you entered actually works, so please visit this link to "
            "activate your account:\n\n  {url}\n\nOnce you activate your "
            "account, you'll automatically be logged in, and you can start "
            "your first order.".format(
                url=self.request.build_absolute_uri(reverse(
                    "users-activation",
                    kwargs={
                        "key": "{key}.{pk}".format(
                            key=self.instance.get_activation_key(),
                            pk=self.instance.pk
                        )
                    }
                ))
            ),
            settings.DEFAULT_FROM_EMAIL,
            [self.instance.email],
            fail_silently=False,
            auth_user=settings.EMAIL_HOST_USER,
            auth_password=settings.EMAIL_HOST_PASSWORD
        )


class DetailsForm(forms.ModelForm):

    password_confirm = forms.CharField(
        widget=forms.widgets.PasswordInput,
        required=False
    )

    class Meta:
        model = get_user_model()
        exclude = [
            "is_referrer", "last_login", "is_superuser",
            "groups", "user_permissions", "is_staff", "is_active"
        ]

    def __init__(self, *a, **kwa):

        self._set_password = None

        forms.ModelForm.__init__(self, *a, **kwa)

        self.fields["password"].widget = forms.widgets.PasswordInput()
        self.fields["password"].required = False

    def clean_email(self):

        email = self.cleaned_data.get("email")

        if self.instance.email == email:
            return email  # No change

        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError(
                "That email is already registered to another account"
            )

        return email

    def clean(self):

        cleaned_data = self.cleaned_data

        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm:
            self._set_password = password

        for key in ("password", "password_confirm"):
            if key in cleaned_data:
                del(cleaned_data[key])

        return cleaned_data

    def save(self, *a, **kwa):

        if self._set_password:
            self.instance.set_password(self._set_password)

        forms.ModelForm.save(self, *a, **kwa)


class ForgotForm(forms.Form):

    email = forms.EmailField()

    def __init__(self, request, *a, **kwa):

        forms.Form.__init__(self, *a, **kwa)

        self.request = request
        self.user = None

    def clean_email(self):

        email = self.cleaned_data.get("email")

        user_model = get_user_model()
        try:
            self.user = user_model.objects.get(email=email)
        except user_model.DoesNotExist:
            raise forms.ValidationError(
                "Apologies, but it appears that this email address is not in "
                "our database."
            )

        return email

    def send(self):
        new_password = self.user.reset_password()
        send_mail(
            subject="Your new password is: {password}\n\n",
            message="When you're ready, you can visit {url} and login with "
                    "your new password, at which point you can change your "
                    "password by visiting the account update page (just click "
                    "your name in the upper-right corner of any page).\n"
                    "\n".format(
                        password=new_password,
                        url=self.request.build_absolute_uri(reverse("login"))
                    ),
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[self.user.email],
            fail_silently=False,
            auth_user=settings.EMAIL_HOST_USER,
            auth_password=settings.EMAIL_HOST_PASSWORD,
        )

src/spirithunter/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.views.generic import TemplateView, View

from spirits.models import Spirit


class IndexView(View):

    template_name = "spirithunter/index.html"

    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("default"))
        return TemplateResponse(
            request=self.request,
            template=self.template_name,
            context={},
        )


class JavascriptVariablesView(TemplateView):

    template_name = "spirithunter/variables.js"

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        context.update({
            "debug": settings.DEBUG,
            "constants": {
                "Spirit": {
                    "ACTIVITY_FROLIC": Spirit.ACTIVITY_FROLIC,
                    "ACTIVITY_JARRED": Spirit.ACTIVITY_JARRED,
                    "ACTIVITY_WANDER": Spirit.ACTIVITY_WANDER,
                    "ACTIVITY_KILLED": Spirit.ACTIVITY_KILLED,
                }
            }
        })
        return context


class DefaultView(LoginRequiredMixin, TemplateView):
    template_name = "spirithunter/default.html"

    def get_context_data(self, **kwargs):
        return TemplateView.get_context_data(self, **kwargs)


class AboutView(TemplateView):
    template_name = "spirithunter/about.html"

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        context.update({
            "header": "About Spirithunter",
            "subheader": "Everything you need to know",
        })
        return context


class RobotsView(TemplateView):
    template_name = "spirithunter/robots.txt"


class HumansView(TemplateView):
    template_name = "spirithunter/humans.txt"

src/spirithunter/templates/spirithunter/about.html
{% extends 'spirithunter/base.html' %}



{% block content %}
  This is the About page
{% endblock content %}

src/spirithunter/templates/spirithunter/base.html
{% load staticfiles %}<!DOCTYPE html>
<!--[if lt IE 7]>    <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>     <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>     <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" href="{% static 'contrib/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'spirithunter/css/spinner.css' %}">

    <script src="{% static 'contrib/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'spirithunter/js/primitives.js' %}"></script>
    <script src="{% url 'javascript' %}"></script>

    {% block css %}{% endblock css %}
    {% block js_header %}{% endblock js_header %}

  </head>
  <body>
    <!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <nav class="navbar navbar-default" role="navigation">

      <div class="container-fluid">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">SpiritHunter</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav">

            {% if user.is_authenticated %}
              <li class="{{ nav.finder     }}"><a href="{% url 'spirits-finder' %}">Find a Fight</a></li>
              <li class="{{ nav.collection }}"><a href="{% url 'users-spirits' url_name=user.url_name %}">Collection</a></li>
              <li class="{{ nav.inventory  }}"><a href="{% url 'users-inventory' url_name=user.url_name %}">Inventory</a></li>
              <li class="{{ nav.sundries   }}"><a href="{% url 'items-shop' %}">Supplies</a></li>
            {% else %}
              <li class="{{ nav.about }}"><a href="{% url 'about' %}">About</a></li>
              <li class="{{ nav.registration }}"><a href="{% url 'login' %}">Register</a></li>
            {% endif %}

            {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}

          </ul>

          {% if not user.is_authenticated %}
            <form class="navbar-form navbar-right" method="post" action="{% url 'login' %}">
              <div class="form-group">
                <input id="id_username" maxlength="254" name="username" type="text" class="form-control" placeholder="Email" />
                <input id="id_password" name="password" type="password" class="form-control" placeholder="Password" />
                {% csrf_token %}
                <input id="id_next" name="next" type="hidden" />
                <input id="id_login" name="login" value="1" type="hidden" />
                <input type="submit" name="s" value="Login" class="btn btn-primary" />
              </div>
            </form>
          {% endif %}

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="col-md-12">
      {% if header %}
        <div class="page-header">
          <h1>{{ header }}{% if subheader %} <small>{{ subheader }}</small>{% endif %}</h1>
        </div>
      {% endif %}
      {% block content %}{% endblock content %}
    </div>

    <script src="{% static 'contrib/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'contrib/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'spirithunter/js/csrf-magic.js' %}"></script>

    {% block js_footer %}{% endblock js_footer %}

    <script src="{% static 'spirithunter/js/location.js' %}"></script>

  </body>
</html>

src/spirithunter/templates/spirithunter/default.html
{% extends 'spirithunter/base.html' %}



{% block content %}
  <div class="text-center">

    <a href="{% url 'spirits-finder' %}" class="btn btn-danger btn-block">Find a Fight</a>
    <p><small>This is where you go looking for trouble.</small></p>

    <a href="{% url 'users-spirits' url_name=user.url_name %}" class="btn btn-primary btn-block">Collection</a>
    <p><small>
      View your collection of spirits, their stats and abilities.  This is also
      where you modify them, set them free, or just let them run around a while
      to gain some HP.
    </small></p>

    <a href="{% url 'users-inventory' url_name=user.url_name %}" class="btn btn-primary btn-block">Inventory</a>
    <p><small>
      Items acquired through battle or via the sundries store are listed here.
    </small></p>

    <a href="{% url 'items-shop' %}" class="btn btn-primary btn-block">Supplies</a>
    <p><small>
      Buy powerups for your spirits including consumables, weapons and armour.
    </small></p>

    <a id="tree-assignment" href="{% url 'api_dispatch_list' api_name='v1' resource_name='tree' %}" class="btn btn-success btn-block ajax-post">Place Your Home Tree Here</a>
    <p><small>
      Your home tree is where your found spirits go when you're not carrying
      them in a jar.  You must return to this tree to make use of them.  Note
      also that you can't just uproot your tree and place it anywhere, as it
      takes 24hours for it to take root and establish itself.  Until that time,
      you cannot make use of your tree and any spirits not currently jarred are
      unavailable to you.
    </small></p>

  </div>
{% endblock content %}



{% block js_footer %}

  {{ block.super }}

  <script>
    $("#tree-assignment").click(function(event){
      event.preventDefault();
      $.post($(this).attr("href"), {}, function(data){
        var coords = data.coordinates;
        alert("Your tree has been planted at (" + coords[1] + "," + coords[0] + ")!  It'll take 24hrs before the tree is available to you.");
      }, "json");
    });
  </script>

{% endblock js_footer %}

src/spirithunter/templates/spirithunter/index.html
{% extends 'spirithunter/base.html' %}



{% block content %}
{% endblock content %}