src/items/urls.py
from __future__ import absolute_import

from django.conf.urls import url
from .views import ShopView as Shop

urlpatterns = [
    url(r"^shoppe/$", Shop.as_view(), name="items-shop"),
]

src/spirithunter/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles import views

from rest_framework import routers

from items.views import (
    ItemViewSet,
    InventoryViewSet,
    RecipeViewSet,
    IngredientViewSet
)
from spirits.views import SpiritViewSet, SpiritFinderViewSet
from users.views import UserViewSet

from .views import IndexView as Index
from .views import JavascriptVariablesView as JavascriptVariables
from .views import HumansView as Humans
from .views import RobotsView as Robots
from .views import AboutView as About
from .views import DefaultView as Default

admin.autodiscover()

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r"users", UserViewSet)
router.register(r"explore", SpiritFinderViewSet)
router.register(r"spirits", SpiritViewSet)
router.register(r"items", ItemViewSet)
router.register(r"inventory", InventoryViewSet)
router.register(r"recipes", RecipeViewSet)
router.register(r"ingredients", IngredientViewSet)

urlpatterns = [

    url(r'^api/', include(router.urls, namespace="drf")),

    url(r'^variables.js', JavascriptVariables.as_view(), name="javascript"),

    url(r'^$', Index.as_view(), name="index"),
    url(r"^about/$", About.as_view(), name="about"),
    url(r"^default/$", Default.as_view(), name="default"),

    url(r"^users/", include("users.urls")),
    url(r"^spirits/", include("spirits.urls")),
    url(r"^items/", include("items.urls")),

    url(r'^humans.txt$', Humans.as_view(), name="humanstxt"),
    url(r'^robots.txt$', Robots.as_view(), name="robotstxt"),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),

]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve, {"show_indexes": True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ]

src/spirits/urls.py
from django.conf.urls import url

from .views import FinderView as Finder
from .views import DetailView as Detail

urlpatterns = [
    url(r"^finder/$", Finder.as_view(), name="spirits-finder"),
    url(r"^(?P<pk>\d+)/$", Detail.as_view(), name="spirits-detail"),
]

src/spirits/models/family.py
from django.contrib.gis.db import models

from django_extensions.db.fields import AutoSlugField


class Family(models.Model):

    class Meta:
        app_label = "spirits"
        verbose_name_plural = "families"

    name = models.CharField(max_length=128)
    slug = AutoSlugField(populate_from="name")
    description = models.TextField()
    stage2_level = models.PositiveIntegerField()
    stage3_level = models.PositiveIntegerField()
    stage4_level = models.PositiveIntegerField()

    def __str__(self):
        return self.name

src/spirits/models/spirit.py
import os
import uuid

from django.conf import settings
from django.contrib.gis.db import models
from django.contrib.gis.geos import fromstr
from django.templatetags.static import static

from django_extensions.db.fields import CreationDateTimeField

from .family import Family
from .level import LevelLadder
from ..managers import SpiritManager


class Spirit(models.Model):

    ACTIVITY_FROLIC = "frolic"  # Tamed and owned by someone, healing
    ACTIVITY_JARRED = "jarred"  # Being carried around by the user
    ACTIVITY_WANDER = "wander"  # Generated by the system, available to fight
    ACTIVITY_KILLED = "killed"  # Killed by a user

    ACTIVITIES = (
        (ACTIVITY_FROLIC, "Frolicking"),
        (ACTIVITY_JARRED, "Jarred"),
        (ACTIVITY_WANDER, "Wandering"),
        (ACTIVITY_KILLED, "Killed"),
    )

    class Meta:
        app_label = "spirits"
        ordering = ("name",)

    # Use a UUID for spirits so they can be sharded if need be
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    family = models.ForeignKey(Family)
    name = models.CharField(max_length=255, blank=True)
    attack = models.PositiveIntegerField(default=0)
    defence = models.PositiveIntegerField(default=0)
    speed = models.PositiveIntegerField(default=0)
    health_maximum = models.PositiveIntegerField(default=0)
    health_current = models.PositiveIntegerField(default=0, db_index=True)
    origin = models.PointField(geography=True)
    location = models.PointField(geography=True, blank=True, null=True)
    created = CreationDateTimeField()
    expires = models.DateTimeField(blank=True, null=True)
    activity = models.CharField(
        choices=ACTIVITIES,
        default=ACTIVITY_WANDER,
        max_length=6,
        db_index=True
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="spirits",
        blank=True,
        null=True
    )
    elements = models.ManyToManyField(
        "aspects.Element", through="ElementalStrength")
    facets = models.ManyToManyField("aspects.Facet", related_name="spirits")
    nationalities = models.ManyToManyField(
        "geography.Country", related_name="citizens")

    # Tally of damage dealt and taken

    damage_dealt_day = models.BigIntegerField(default=0, editable=False)
    damage_dealt_night = models.BigIntegerField(default=0, editable=False)
    damage_dealt_moon_new = models.BigIntegerField(default=0, editable=False)
    damage_dealt_moon_full = models.BigIntegerField(default=0, editable=False)
    damage_dealt_water = models.BigIntegerField(default=0, editable=False)
    damage_dealt_nature = models.BigIntegerField(default=0, editable=False)
    damage_dealt_hot = models.BigIntegerField(default=0, editable=False)
    damage_dealt_cold = models.BigIntegerField(default=0, editable=False)
    damage_dealt_wind = models.BigIntegerField(default=0, editable=False)

    damage_taken_day = models.BigIntegerField(default=0, editable=False)
    damage_taken_night = models.BigIntegerField(default=0, editable=False)
    damage_taken_moon_new = models.BigIntegerField(default=0, editable=False)
    damage_taken_moon_full = models.BigIntegerField(default=0, editable=False)
    damage_taken_water = models.BigIntegerField(default=0, editable=False)
    damage_taken_nature = models.BigIntegerField(default=0, editable=False)
    damage_taken_hot = models.BigIntegerField(default=0, editable=False)
    damage_taken_cold = models.BigIntegerField(default=0, editable=False)
    damage_taken_wind = models.BigIntegerField(default=0, editable=False)

    experience = models.BigIntegerField(default=0, editable=False)
    level = models.PositiveIntegerField(editable=False)

    objects = SpiritManager()

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self._element_path = None

    def __str__(self):
        return self.name or self.family.name

    @property
    def image16(self):
        return self._get_image(size=16)

    @property
    def image32(self):
        return self._get_image(size=32)

    @property
    def image64(self):
        return self._get_image(size=64)

    @property
    def image128(self):
        return self._get_image(size=128)

    @property
    def image256(self):
        return self._get_image(size=256)

    def get_absolute_url(self):
        return "/spirit/%s" % self.pk

    def get_ladder(self):
        return self.family.ladder.get(level=self.level)

    def get_origin_string(self):
        return "{lat:0.4f}, {lng:0.4f}".format(
            lat=self.origin.y, lng=self.origin.x)

    def get_location_string(self):
        return "{lat:0.4f}, {lng:0.4f}".format(
            lat=self.location.y, lng=self.location.x)

    def is_near(self, spirit, radius=100):
        """
        Returns True if the spirit in question is within 100 metres of this
        spirit.
        """
        return self.__class__.objects.filter(
            location__distance_lte=(
                fromstr("POINT(%s %s)" % (self.location.x, self.location.y)),
                radius
            ),
            pk=spirit.pk
        ).exists()

    def give_xp(self, amount):

        report = {
            "experience": amount,
        }

        self.experience += amount  # ExpEgg anyone?

        # TODO: Account for cases where the spirit skips a level or more

        xp_required = self.family.ladder.get(
            level=int(self.level)+1).xp_required

        if self.experience >= xp_required:

            self.level += 1

            new_stats = LevelLadder.objects.get(
                level=self.level,
                family=self.family
            )
            for attribute in ("attack", "defence", "speed"):
                setattr(self, attribute, getattr(new_stats, attribute))

            self.health_maximum = new_stats.health

            strengths = self.elemental_strengths.filter(
                strength__gte=0
            ).values_list("pk", flat=True)
            for i in range(0, len(strengths)-1):
                ElementalStrength.objects.filter(pk=strengths[i]).update(
                    strength=getattr(new_stats, "level_up_element{e}".format(
                        e=i+1
                    ))
                )

            milestones = (
                self.family.stage2_level,
                self.family.stage3_level,
                self.family.stage4_level
            )
            if self.level in milestones:
                self._add_elemental()

        self.save()

        return report

    def _add_elemental(self):

        current_total = self.elemental_strengths.filter(
            strength__gte=0).count()
        fights = ElementalStrength.objects.filter(
            spirit__defending_encounters__user_spirit=self,
            spirit__defending_encounters__result__in=(
                Encounter.RESULT_CAPTURED,
                Encounter.RESULT_RELEASED
            ),
            strength__gte=0
        )

        elements = {}
        for fight in fights:
            if fight.element not in elements:
                elements[fight.element] = 0
            elements[fight.element] += 1

        element_to_add = elements[sorted(elements.keys(), lambda e: e.pk)[0]]

        strength = getattr(
            self.family.ladder.get(pk=self.level),
            "level_up_element{e}".format(e=current_total+1)
        )

        ElementalStrength.objects.create(
            spirit=self,
            element=element_to_add,
            strength=strength
        )

    def _get_image(self, size=32):
        """
        Each spirit is a combination of the family + any elements attached, so
        this can be compiled logically as a URL.
        """

        if not self._element_path:

            elements = self.elements.filter(
                applications__strength__gt=0
            ).order_by(
                "name"
            ).values_list(
                "slug",
                flat=True
            )

            self._element_path = os.path.join(*elements)

        return static("spirits/img/{size}/{family}/{elements}.png".format(
            size=size,
            family=self.family.slug,
            elements=self._element_path
        ))


class ElementalStrength(models.Model):
    """
    """

    class Meta:
        app_label = "spirits"
        unique_together = ("spirit", "element")
        ordering = ("created", "element")

    spirit = models.ForeignKey("Spirit", related_name="elemental_strengths")
    element = models.ForeignKey("aspects.Element", related_name="applications")
    strength = models.IntegerField(
        help_text="Positive number for affinities, negative for weaknesses")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{element}: {strength}".format(
            element=self.element,
            strength=self.strength
        )

src/spirits/views.py
import random

from math import sin, cos

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from rest_framework.exceptions import ValidationError
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import AllowAny

from aspects.models import Element
from spirithunter.logging import LogMixin

from .models.spirit import Spirit
from .serializers import SpiritSerializer


class SpiritViewSet(ModelViewSet):
    queryset = Spirit.objects.all()
    serializer_class = SpiritSerializer
    http_method_names = ("get",)


class SpiritFinderViewSet(LogMixin, ModelViewSet):
    """
    Currently, this is designed to work via the REST API, but could (should?)
    work with websockets to do cool stuff like auto-initiating a fight.
    """

    SPIRITS_TO_GENERATE = 5
    SPAWN_RADIUS = 50

    serializer_class = SpiritSerializer
    permission_classes = (AllowAny,)
    http_method_names = ("get",)
    queryset = Spirit.objects.none()

    def get_queryset(self):

        lat, lng = (self.request.location.y, self.request.location.x)

        if lat > 80 or lat < -80:
            raise ValidationError("Invalid lat value: %s" % lat)

        if lng > 180 or lng < -180:
            raise ValidationError("Invalid lng value: %s" % lng)

        low, high = self._get_levels()

        spirits = list(Spirit.objects.filter(
            activity=Spirit.ACTIVITY_WANDER,
            health_current__gt=0,
            location__distance_lte=(self.request.location, self.SPAWN_RADIUS)
        ))

        while len(spirits) < self.SPIRITS_TO_GENERATE:
            spirits.append(self._generate_spirit(lat, lng, low, high))

        return spirits

    def _get_levels(self):

        low, high = 1, 1
        if self.request.user.is_authenticated():
            spirit_levels = sorted(self.request.user.spirits.filter(
                activity=Spirit.ACTIVITY_JARRED
            ).values_list("level", flat=True))
            if spirit_levels:
                low, high = spirit_levels[0], spirit_levels[-1]

        return low, high

    def _get_nearby_location(self, lat, lng):
        """
        This is magic that I honestly don't understand, but basically it takes
        a centre point and gives you a random location near to that point.

        :param lat: Degrees latitude
        :param lng: Degrees longitude
        :return: A new lat,lng coordinate
        """

        centre_x = float(lat)
        centre_y = float(lng)
        r = random.uniform(0, self.SPAWN_RADIUS)
        a = random.uniform(0, 360)

        return (
            centre_x,
            centre_y,
            centre_x + ((r * cos(a)) / settings.M_LNG),
            centre_y + ((r * sin(a)) / settings.M_LAT)
        )

    def _generate_spirit(self, lat, lng, low, high):

        centre_x, centre_y, target_x, target_y = self._get_nearby_location(
            lat, lng)

        self.logger.debug("Creating a spirit at %s,%s", target_x, target_y)

        return Spirit.objects.create_for_environment(
            centre=(centre_x, centre_y),
            target=(target_x, target_y),
            level_low=low,
            level_high=high
        )


class FinderView(LogMixin, LoginRequiredMixin, TemplateView):

    template_name = "spirits/base.html"

    def get_context_data(self, **kwargs):
        self.logger.debug("get_context_data: start")
        context = TemplateView.get_context_data(self, **kwargs)
        context.update({
            "available_spirits": Spirit.objects.filter(
                owner=self.request.user,
                activity=Spirit.ACTIVITY_JARRED,
                health_current__gt=0
            ).prefetch_related("elements", "facets", "nationalities")
        })
        self.logger.debug("get_context_data: stop")
        return context


class DetailView(TemplateView):

    template_name = "spirits/detail.html"

    def get_context_data(self, **kwargs):

        context = TemplateView.get_context_data(self, **kwargs)

        spirit = get_object_or_404(Spirit, pk=kwargs["pk"])
        permissions = {
            "is_administrator": spirit.owner == self.request.user
        }

        context.update({
            "spirit": spirit,
            "elements": {
                "positive": Element.objects.filter(
                    applications__spirit=spirit,
                    applications__strength__gte=0
                ),
                "negative": Element.objects.filter(
                    applications__spirit=spirit,
                    applications__strength__lt=0
                ),
            },
            "permissions": permissions
        })

        return context

src/spirits/templates/spirits/base.html
{% extends 'spirithunter/base.html' %}
{% load staticfiles %}



{% block css %}

  {{ block.super }}

  <link rel="stylesheet" type="text/css" href="{% static 'contrib/leafletjs/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'contrib/flags/stylesheets/flags16.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'spirits/css/general.css' %}" />

{% endblock css %}



{% block content %}

  {% include 'spirits/finder.html' %}
  {% include 'spirits/chooser.html' %}
  {% include 'spirits/encounter.html' %}
  {% include 'spirits/spoils.html' %}
  {% include 'spirits/defeated.html' %}

{% endblock content %}



{% block js_footer %}

  {{ block.super }}

  <script type="text/javascript" src="{% static 'contrib/leafletjs/leaflet.js' %}"></script>
  <script type="text/javascript" src="{% static 'encounters/js/general.js' %}"></script>

{% endblock js_footer %}

src/spirits/templates/spirits/chooser.html
<div id="chooser" class="chooser">
  {% for spirit in available_spirits %}
    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 text-center">
      <div class="spirit">
        <a
          href="#"
          data-name="{{ spirit.name }}"
          data-pk="{{ spirit.pk }}"
          data-image64="{{ spirit.image64 }}"
          data-level="{{ spirit.level }}"
          data-health_current="{{ spirit.health_current }}"
          data-health_maximum="{{ spirit.health_maximum }}"
          data-elements="{% for element in spirit.elements.all %}{{ element.image16 }}{% if not forloop.last %},{% endif %}{% endfor %}"
        >
          <img src="{{ spirit.image64 }}" width="64" height="64" />
          <h5>{{ spirit.name }} (id:{{ spirit.pk }})</h5>
        </a>
      </div>
      <span class="attributes elements">
        {% for element in spirit.elements.all %}
          <img src="{{ element.image16 }}" width="16" height="16" alt="{{ element.name }}" />
        {% endfor %}
      </span>
      <span class="attributes facets">
        {% for facet in spirit.facets.all %}
          <img src="{{ facet.image16 }}" width="16" height="16" alt="{{ facet.name }}" />
        {% endfor %}
      </span>
      <span class="attributes nationalities f16">
        {% for nationality in spirit.nationalities.all %}
          <span class="flag {{ nationality.country.code|lower }}" title="{{ nationality.country.name }}"></span>
        {% endfor %}
      </span>
    </div>
  {% endfor %}
</div>

src/spirits/templates/spirits/detail.html
{% extends 'spirithunter/base.html' %}
{% load staticfiles %}



{% block css %}

  {{ block.super }}

  <link rel="stylesheet" type="text/css" href="{% static 'contrib/flags/stylesheets/flags32.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'spirits/css/general.css' %}" />
  <style type="text/css">
    .noname {
      font-style: italic;
      color: #cccccc;
    }
  </style>

{% endblock css %}



{% block content %}

  <div class="col-md-4 pull-left">
    <img src="{{ spirit.image256 }}" width="256" height="256" alt="">
  </div>
  <div class="col-md-8 pull-left">
    <h1>
      {% if spirit.name %}
        {{ spirit.name }}
      {% else %}
        <span class="noname">Unnamed</span>
      {% endif %}
      {% if permissions.is_administrator %}
        <div class="pull-right"><a href="#" class="btn btn-primary btn-mini">Edit</a></div>
      {% endif %}
    </h1>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Stats</h3>
      </div>
      <div class="panel-body">
        <table class="table table-responsive table-striped">
          <tr class="hidden-md"><th>Level</th><td>{{ spirit.level }}</td></tr>
          <tr><th>Family</th><td>{{ spirit.family.name }}</td></tr>
          <tr><th>ATK</th><td>{{ spirit.attack }}</td></tr>
          <tr><th>DEF</th><td>{{ spirit.defence }}</td></tr>
          <tr><th>HP</th><td>{{ spirit.health_current }} / {{ spirit.health_maximum }}</td></tr>
          <tr><th>SP</th><td>{{ spirit.speed }}</td></tr>
          <tr><th>Origin</th><td>{{ spirit.get_origin_string }}</td></tr>
          {% if spirit.activity == spirit.ACTIVITY.WANDER %}
            <tr><th>Location</th><td>{{ spirit.get_location_string }}</td></tr>
          {% endif %}
          <tr><th>Spawned</th><td>{{ spirit.created }}</td></tr>
          <tr><th>Currently</th><td><span id="current-activity">{{ spirit.get_activity_display }}</span></td></tr>
          {% if spirit.owner %}
            <tr><th>Owner</th><td>{{ spirit.owner }}</td></tr>
          {% endif %}
          <tr>
            <th>Positive Elements</th>
            <td>
              {% for element in elements.positive %}
                <img src="{{ element.image32 }}" title="{{ element.name }}" />
              {% endfor %}
            </td>
          </tr>
          <tr>
            <th>Negative Elements</th>
            <td>
              {% for element in elements.negative %}
                <img src="{{ element.image32 }}" title="{{ element.name }}" />
              {% endfor %}
            </td>
          </tr>
          <tr>
            <th>Facets</th>
            <td>
              {% for facet in spirit.facets.all %}
                <img src="{{ facet.image32 }}" title="{{ facet.name }}"/>
              {% endfor %}
            </td>
          </tr>
          <tr>
            <th>Nationalities</th>
            <td class="icons f32">
              {% for nationality in spirit.nationalities.all %}
                <span class="flag {{ nationality.country.code|lower }}" title="{{ nationality.country.name }}"></span>
              {% endfor %}
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  {% if permissions.is_administrator %}
    <div class="clearfix"></div>
    <div class="btn-group btn-group-justified col-md-12">
      <div class="btn-group">
        <button type="button" class="btn btn-default btn-success activity-change" data="frolicking">Frolic</button>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-default btn-primary activity-change" data="jarred">Jar</button>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-default btn-danger activity-change" data="released">Release</button>
      </div>
    </div>
  {% endif %}

{% endblock content %}



{% block js_footer %}

  {{ block.super }}

  <script>

    var $current_activity = $("#current-activity");
    function handle_activity_change(){
      var activity = $(this).attr("data");
      $.ajax({
        headers : {
          "Accept": "application/json",
          "Content-Type": "application/json"
        },
        url: window.spirithunter.urls.api.v1.spirits.detail.replace("0000", {{ spirit.pk }}),
        type: "PATCH",
        data: JSON.stringify({activity: window.spirithunter.constants.activities[activity]}),
        success: function(response, textStatus, jqXhr) {
          alert(activity.capitalise() + "!");
          $current_activity.html(activity.capitalise());
          if (activity == "released") {
            window.location.reload();
          }
        },
        error: function(jqXHR, textStatus, errorThrown) {
          console.log(textStatus, errorThrown);
        }
      });
    }

    $(".activity-change").click(handle_activity_change);

  </script>

{% endblock js_footer %}

src/spirits/templates/spirits/encounter.html
<div id="encounter" class="encounter">
  <div id="theatre" class="theatre">
    <div class="attacker col-xs-6 col-md-6"></div>
    <div class="defender col-xs-6 col-md-6"></div>
    <div class="attacker-elements col-xs-6 col-md-6 text-center"></div>
    <div class="defender-elements col-xs-6 col-md-6 text-center"></div>
    <div class="clearfix"></div>
  </div>
  <div id="stats" class="stats">
    <div class="attacker col-xs-6 col-md-6">
      <div class="health">
        <span class="health-current">0</span> /
        <span class="health-maximum">0</span>
      </div>
      <div class="level">Level <span class="level-value">0</span></div>
    </div>
    <div class="defender col-xs-6 col-md-6">
      <div class="health">
        <span class="health-current">0</span> /
        <span class="health-maximum">0</span>
      </div>
      <div class="level">Level <span class="level-value">0</span></div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div id="options" class="options">
    <a href="#" id="use-attack" class="btn btn-danger btn-block">Attack</a>
    <a href="#" id="use-magic" class="btn btn-success btn-block">Magic</a>
    <a href="#" id="use-item" class="btn btn-info btn-block">Item</a>
    <a href="#" id="escape" class="btn btn-default btn-block">Escape</a>
  </div>
</div>

src/spirits/templates/spirits/finder.html
<div id="finder" class="finder"><div class="spinner"></div></div>

src/spirits/templates/spirits/spoils.html
<div id="spoils" class="spoils col-md-12 text-center">
  <p>
    <span id="spoils-winner-name"></span> will gain <span id="spoils-xp"></span> XP!
  </p>
  <div class="choice">
    <a id="spoils-keep" href="#" class="btn btn-primary">Keep <span id="spoils-loser-name"></span> as your own</a>
    <a id="spoils-item" href="#" class="btn btn-primary">Let them go</a>
  </div>
  <p>Releasing spirits often results in rewards in the form of items and/or coins.</p>
</div>